"""Filesystem-backed progress journal adapter."""

from . import handoff, paths
from .filesystem_journal import FilesystemProgressJournal
from .handoff import (
    ImplementProgressEnvelope,
    fallback_implement_progress_envelope,
    parse_implement_progress_envelope,
    render_handoff_markdown_entry,
)
from .iteration_telemetry import (
    append_run,
    write_iteration_telemetry,
)
from .paths import (
    FEATURE_HANDOFF_FILENAME,
    FEATURE_ITERATION_REPORT_FILENAME,
    FEATURE_RUN_LOG_FILENAME,
    PROGRESS_DIRNAME,
    PROGRESS_FEATURES_DIRNAME,
    PROGRESS_REVIEWERS_DIRNAME,
    PROGRESS_RUNS_DIRNAME,
    REVIEWERS_STATE_FILENAME,
    RUNS_JSONL_FILENAME,
    feature_dir_path,
    features_dir,
    handoff_markdown_path,
    handoff_markdown_reference,
    handoff_markdown_template_reference,
    iteration_report_path,
    iteration_report_reference,
    progress_dir,
    reviewers_state_path,
    run_feature_log_filename,
    run_feature_log_path,
    run_feature_log_reference,
    run_feature_log_template_reference,
    runs_dir,
    runs_jsonl_path,
    runs_jsonl_reference,
    sanitize_feature_id_for_log,
)

__all__ = [
    "handoff",
    "paths",
    "FilesystemProgressJournal",
    "ImplementProgressEnvelope",
    "parse_implement_progress_envelope",
    "fallback_implement_progress_envelope",
    "render_handoff_markdown_entry",
    "append_run",
    "write_iteration_telemetry",
    "PROGRESS_DIRNAME",
    "PROGRESS_RUNS_DIRNAME",
    "PROGRESS_FEATURES_DIRNAME",
    "PROGRESS_REVIEWERS_DIRNAME",
    "RUNS_JSONL_FILENAME",
    "FEATURE_RUN_LOG_FILENAME",
    "FEATURE_HANDOFF_FILENAME",
    "FEATURE_ITERATION_REPORT_FILENAME",
    "REVIEWERS_STATE_FILENAME",
    "progress_dir",
    "runs_dir",
    "features_dir",
    "feature_dir_path",
    "runs_jsonl_path",
    "runs_jsonl_reference",
    "reviewers_state_path",
    "sanitize_feature_id_for_log",
    "run_feature_log_filename",
    "run_feature_log_path",
    "run_feature_log_reference",
    "run_feature_log_template_reference",
    "handoff_markdown_path",
    "handoff_markdown_reference",
    "handoff_markdown_template_reference",
    "iteration_report_path",
    "iteration_report_reference",
]
